use crosshook_core::export::check_launcher_exists;
use crosshook_core::profile::{GameProfile, LaunchSection};
use std::fs;
use tempfile::tempdir;

use crate::commands::profile::shared::cleanup_launchers_for_profile_delete;
use crate::commands::profile::tests::helpers::steam_profile;

fn create_watermarked_launcher_files(script_path: &str, desktop_path: &str) {
    fs::create_dir_all(
        std::path::Path::new(script_path)
            .parent()
            .expect("script parent"),
    )
    .expect("script dirs");
    fs::create_dir_all(
        std::path::Path::new(desktop_path)
            .parent()
            .expect("desktop parent"),
    )
    .expect("desktop dirs");
    fs::write(
        script_path,
        "#!/usr/bin/env bash\n# Generated by CrossHook\n",
    )
    .expect("write script");
    fs::write(
        desktop_path,
        "[Desktop Entry]\nName=Test Game - Trainer\nComment=Generated by CrossHook\n",
    )
    .expect("write desktop");
}

#[test]
fn cleanup_launchers_for_profile_delete_uses_derived_steam_paths() {
    let temp = tempdir().expect("temp dir");
    let home = temp.path().to_string_lossy().into_owned();
    let profile = steam_profile(&home);
    let steam_root = format!("{home}/.local/share/Steam");

    let info = check_launcher_exists(
        &profile.steam.launcher.display_name,
        &profile.steam.app_id,
        &profile.trainer.path,
        &home,
        &steam_root,
    )
    .expect("check launcher exists");
    create_watermarked_launcher_files(&info.script_path, &info.desktop_entry_path);

    let result = cleanup_launchers_for_profile_delete("test-profile", &profile)
        .expect("cleanup should succeed");

    assert!(result.is_some());
    assert!(!std::path::Path::new(&info.script_path).exists());
    assert!(!std::path::Path::new(&info.desktop_entry_path).exists());
}

#[test]
fn cleanup_launchers_for_profile_delete_skips_native_profiles() {
    let profile = GameProfile {
        launch: LaunchSection {
            method: "native".to_string(),
            ..Default::default()
        },
        ..GameProfile::default()
    };

    let result = cleanup_launchers_for_profile_delete("native-profile", &profile)
        .expect("native cleanup should not fail");

    assert!(result.is_none());
}
