using CrossHookEngine.App.Services;

namespace CrossHookEngine.App.Tests;

public sealed class SteamExternalLauncherExportServiceTests
{
    [Fact]
    public void ExportLaunchers_WritesTrainerScriptAndDesktopEntryToUserHome()
    {
        using TestWorkspace workspace = new TestWorkspace();
        string launcherIconPath = workspace.CreateFile("icons", "mgs-tpp-icon.png");
        SteamExternalLauncherExportRequest request = new SteamExternalLauncherExportRequest
        {
            LauncherName = "MGS_TPP",
            TrainerPath = @"D:\Games\Trainers\StandAlone\mgs-tpp-fling.exe",
            LauncherIconPath = launcherIconPath,
            SteamAppId = "287700",
            SteamCompatDataPath = "/mnt/sdb/SteamLibrary/steamapps/compatdata/287700",
            SteamProtonPath = "/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/proton",
            SteamClientInstallPath = "/home/yandy/.local/share/Steam",
            TargetHomePath = workspace.RootPath
        };

        SteamExternalLauncherExportResult result = SteamExternalLauncherExportService.ExportLaunchers(request);

        string expectedScriptPath = workspace.GetPath(".local", "share", "crosshook", "launchers", "mgs-tpp-trainer.sh");
        string expectedDesktopEntryPath = workspace.GetPath(".local", "share", "applications", "crosshook-mgs-tpp-trainer.desktop");

        Assert.Equal("MGS_TPP", result.DisplayName);
        Assert.Equal("mgs-tpp", result.LauncherSlug);
        Assert.Equal(expectedScriptPath, result.ScriptPath);
        Assert.Equal(expectedDesktopEntryPath, result.DesktopEntryPath);
        Assert.True(File.Exists(expectedScriptPath));
        Assert.True(File.Exists(expectedDesktopEntryPath));

        string scriptContent = File.ReadAllText(expectedScriptPath);
        Assert.Contains("# MGS_TPP - Trainer launcher", scriptContent);
        Assert.Contains("# Generated by CrossHook", scriptContent);
        Assert.Contains("# https://github.com/yandy-r/crosshook", scriptContent);
        Assert.Contains("export STEAM_COMPAT_DATA_PATH='/mnt/sdb/SteamLibrary/steamapps/compatdata/287700'", scriptContent);
        Assert.Contains("export STEAM_COMPAT_CLIENT_INSTALL_PATH='/home/yandy/.local/share/Steam'", scriptContent);
        Assert.Contains("PROTON='/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/proton'", scriptContent);
        Assert.Contains(@"TRAINER_WINDOWS_PATH='D:\Games\Trainers\StandAlone\mgs-tpp-fling.exe'", scriptContent);
        Assert.Contains("exec \"$PROTON\" run \"$TRAINER_WINDOWS_PATH\"", scriptContent);

        string desktopContent = File.ReadAllText(expectedDesktopEntryPath);
        Assert.Contains("Name=MGS_TPP - Trainer", desktopContent);
        Assert.Contains("Comment=Trainer launcher for MGS_TPP. Generated by CrossHook: https://github.com/yandy-r/crosshook", desktopContent);
        Assert.Contains($"Exec=/bin/bash {expectedScriptPath}", desktopContent);
        Assert.Contains($"Icon={launcherIconPath}", desktopContent);
    }

    [Fact]
    public void Validate_ReturnsInvalid_WhenTargetHomePathIsMissing()
    {
        SteamExternalLauncherExportRequest request = new SteamExternalLauncherExportRequest
        {
            LauncherName = "MGS_TPP",
            TrainerPath = @"D:\Games\Trainers\StandAlone\mgs-tpp-fling.exe",
            SteamAppId = "287700",
            SteamCompatDataPath = "/mnt/sdb/SteamLibrary/steamapps/compatdata/287700",
            SteamProtonPath = "/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/proton",
            SteamClientInstallPath = "/home/yandy/.local/share/Steam"
        };

        SteamExternalLauncherExportValidationResult result = SteamExternalLauncherExportService.Validate(request);

        Assert.False(result.IsValid);
        Assert.Contains("home path", result.ErrorMessage, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void ExportLaunchers_UsesDefaultIcon_WhenLauncherIconPathIsBlank()
    {
        using TestWorkspace workspace = new TestWorkspace();
        SteamExternalLauncherExportRequest request = new SteamExternalLauncherExportRequest
        {
            LauncherName = "MGS_TPP",
            TrainerPath = @"D:\Games\Trainers\StandAlone\mgs-tpp-fling.exe",
            SteamAppId = "287700",
            SteamCompatDataPath = "/mnt/sdb/SteamLibrary/steamapps/compatdata/287700",
            SteamProtonPath = "/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/proton",
            SteamClientInstallPath = "/home/yandy/.local/share/Steam",
            TargetHomePath = workspace.RootPath
        };

        SteamExternalLauncherExportResult result = SteamExternalLauncherExportService.ExportLaunchers(request);

        string desktopContent = File.ReadAllText(result.DesktopEntryPath);
        Assert.Contains("Icon=applications-games", desktopContent);
    }

    [Fact]
    public void Validate_ReturnsInvalid_WhenLauncherIconPathIsNotAnImage()
    {
        using TestWorkspace workspace = new TestWorkspace();
        string launcherIconPath = workspace.CreateFile("icons", "mgs-tpp-icon.txt");
        SteamExternalLauncherExportRequest request = new SteamExternalLauncherExportRequest
        {
            LauncherName = "MGS_TPP",
            TrainerPath = @"D:\Games\Trainers\StandAlone\mgs-tpp-fling.exe",
            LauncherIconPath = launcherIconPath,
            SteamAppId = "287700",
            SteamCompatDataPath = "/mnt/sdb/SteamLibrary/steamapps/compatdata/287700",
            SteamProtonPath = "/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/proton",
            SteamClientInstallPath = "/home/yandy/.local/share/Steam",
            TargetHomePath = workspace.RootPath
        };

        SteamExternalLauncherExportValidationResult result = SteamExternalLauncherExportService.Validate(request);

        Assert.False(result.IsValid);
        Assert.Contains("PNG or JPG", result.ErrorMessage, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void ResolveTargetHomePath_FallsBackToSteamClientInstallPath_WhenPreferredHomeIsInsideCompatdata()
    {
        string resolvedHomePath = SteamExternalLauncherExportService.ResolveTargetHomePath(
            preferredHomePath: "/home/yandy/.local/share/Steam/steamapps/compatdata/3109640506/pfx/dosdevices/c:/users/steamuser",
            steamClientInstallPath: "/home/yandy/.local/share/Steam");

        Assert.Equal("/home/yandy", resolvedHomePath);
    }

    [Fact]
    public void CombineHostUnixPath_UsesForwardSlashes_ForLauncherTargets()
    {
        string combinedPath = SteamExternalLauncherExportService.CombineHostUnixPath(
            "/home/yandy",
            ".local/share/crosshook/launchers",
            "mgs-tpp-trainer.sh");

        Assert.Equal("/home/yandy/.local/share/crosshook/launchers/mgs-tpp-trainer.sh", combinedPath);
    }
}
